version: '3.3'
services:

  yoga_postgres:
    container_name: yoga_postgres
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s


  backend:
    build: .
    restart: always
    volumes:
      - backend_static_value:/app/static/
      - backend_media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      yoga_postgres:
        condition: service_healthy
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: 'yoga_postgres'
      DB_PORT: 5432

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - backend_static_value:/var/html/static/
      - backend_media_value:/var/html/media/

    depends_on:
      - backend

volumes:
  backend_static_value:
  backend_media_value: