# Generated by Django 2.2.19 on 2024-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0002_auto_20241114_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
