# Generated by Django 2.2.19 on 2024-11-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_app", "0004_auto_20241114_1630"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
