# Generated by Django 4.2.17 on 2025-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_app", "0008_workoutstatistic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
