# Generated by Django 4.2.17 on 2025-01-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_app", "0010_alter_workoutstatistic_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
