# Generated by Django 4.2.17 on 2025-01-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_app", "0011_alter_exercise_description_alter_exercise_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutstatistic",
            name="count_exercises",
            field=models.IntegerField(default=0),
        ),
    ]
