# Generated by Django 4.2.17 on 2025-01-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_app", "0012_workoutstatistic_count_exercises"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="training",
            name="name",
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name="trainingrequest",
            name="duration",
            field=models.IntegerField(default=60),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("published_date", models.DateField(auto_now_add=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                (
                    "related_exercises",
                    models.ManyToManyField(blank=True, to="yoga_app.exercise"),
                ),
            ],
        ),
    ]
