# Generated by Django 4.2.17 on 2025-01-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "yoga_app",
            "0013_alter_exercise_description_alter_exercise_name_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
