# Generated by Django 4.2.17 on 2025-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_app", "0015_programrequest_programitem_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programitem",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=9,
            ),
        ),
    ]
