# Generated by Django 4.2.17 on 2025-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_app", "0016_alter_programitem_weekday"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="complexity",
            field=models.SmallIntegerField(
                choices=[("Easy", 1), ("Medium", 2), ("Hard", 3)], default=1
            ),
            preserve_default=False,
        ),
    ]
