# Generated by Django 4.2.17 on 2025-04-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_app", "0019_style_training_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrequest",
            name="complexity",
            field=models.SmallIntegerField(
                choices=[("Easy", 1), ("Medium", 2), ("Hard", 3)], default=1
            ),
        ),
        migrations.AddField(
            model_name="trainingrequest",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_requests",
                to="yoga_app.style",
            ),
        ),
    ]
