# Generated by Django 4.2.17 on 2025-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_app", "0021_exercisetype_alter_trainingrequest_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="type",
        ),
        migrations.AddField(
            model_name="exercise",
            name="types",
            field=models.ManyToManyField(
                related_name="exercises",
                to="yoga_app.exercisetype",
                verbose_name="Типы асан",
            ),
        ),
    ]
